name: Refresh GitHub Pages on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  refresh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0

    - name: Install Git LFS and Checkout Main
      run: |
        git lfs install
        git fetch origin main
        git checkout main

    - name: Update timestamp to trigger Pages rebuild
      run: |
        echo "Triggered by tag $GITHUB_REF" > deploy-log.txt
        date >> deploy-log.txt
        touch .nojekyll

    - name: Commit and Push to Main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .nojekyll deploy-log.txt
        git commit -m "Refresh Pages from tag $GITHUB_REF" || echo "No changes to commit"
        git push origin main
