name: Deploy Unity WebGL Build on Tag

on:
  push:
    tags:
      - 'v*'  # Example: v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0  # Needed for full Git history and tags

    - name: Install Git LFS and fetch files
      run: |
        git lfs install
        git lfs pull

    - name: Switch to main branch
      run: |
        git fetch origin main
        git checkout main

    - name: Ensure .nojekyll exists to allow _Framework folders
      run: |
        echo "Triggered by tag $GITHUB_REF" > deploy-log.txt
        date >> deploy-log.txt
        touch .nojekyll

    - name: Commit and push to main with PAT
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
        git add .nojekyll deploy-log.txt
        git commit -m "Refresh GitHub Pages from tag $GITHUB_REF" || echo "No changes to commit"
        git push origin main
