name: Deploy WebGL on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./
        exclude_assets: .github
