name: Deploy WebGL from Zip on Tag

on:
  push:
    tags:
      - 'v*'  # Deploy on tag push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Unzip WebGL Build
      run: |
        mkdir output
        unzip webgl-build.zip -d output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}  # Replace with github_token if it works
        publish_dir: ./output
